Nodejs week2
27ManishaPatel/hyf-homework pull request #18
Opened 2022-09-16 12:27 UTC by 27ManishaPatel

2022-09-17 20:26 UTC, itsgauravsaxena requested changes

2022-09-17 20:26 UTC, itsgauravsaxena commented on nodejs/week2/hw-warmup/app.js
> +                console.log(new String(obj[objKey]))
Always good idea to remove console logs :)

2022-09-17 20:26 UTC, itsgauravsaxena commented on nodejs/week2/hw-warmup/app.js
> +            res.send(data);
This `data` will not work. You should return `obj ` instead

2022-10-06 08:52 UTC, andrii1 commented on nodejs/week2/class-exercise/app.js
> +const router = express.Router();
is it convenient for you to have class exercises in the same branch? I also tried that, but then messed up node modules 😅

2022-10-06 08:52 UTC, andrii1 commented on nodejs/week2/hw-warmup/app.js
> +      }else if (fields != undefined) {
some formatting issues, check if your prettier work ok :)

2022-10-13 11:02 UTC, 27ManishaPatel commented on nodejs/week2/class-exercise/app.js
> +const router = express.Router();
Yes it is good to record the work and exercise and I messed up with node modules in the beginning but then I learned That how to come out with all that 😁

2022-10-13 11:06 UTC, merged