React react1 week2
27ManishaPatel/hyf-homework pull request #22
Opened 2022-10-03 21:01 UTC by 27ManishaPatel

2022-10-05 16:56 UTC, annamourasobral requested changes
Hey, Manisha, I see improvement in your code, keep going!

I noticed that you are struggling with how to build the hierarchy of components, and I thought should be interesting to share this [article from React's documentation](https://reactjs.org/docs/thinking-in-react.html) that is very useful!

Nice styling by the way, what about centralizing the container on the screen and giving some margin to the Add button? 

That's all for today..
Happy coding! 👩🏻‍💻

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/class-exercise/src/App.js
> +        <button onClick={() => { setCount(count + 1) }}>Click </button>
setCount isn't an object, it's a function, so it shouldn't be wrapped in curly braces  =)
```suggestion
        <button onClick={() =>  setCount(count + 1) }>Click </button>
```

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Main.jsx
> +const ToDoLists = [
now that the app is growing is probably a good time to store this data in a file like data.js, fx. =)

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Main.jsx
> +    const DeleteList = (id) => {
The naming is confusing. You're deleting an item, not a List.

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Main.jsx
> +    const CheckedList = (id)=> {
The same naming problem here.

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Main.jsx
> +    function ToDoListItems (props) {
This should be another component.

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Main.jsx
> +    const AddList = ()=>{
functions should be grouped

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/App.js
> +import Header from './Header';
import React as well =)

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Header.jsx
> +import Timer from './Timer'
import React

2022-10-05 16:56 UTC, annamourasobral commented on react/react1/week2/to-do-app/src/Footer.jsx
> +export default function Footer () {
import React

2022-10-10 09:27 UTC, 27ManishaPatel commented on react/react1/week2/to-do-app/src/Main.jsx
> +    const DeleteList = (id) => {
yes true 🙈

2022-10-20 17:48 UTC, andrii1 commented on react/react1/week2/to-do-app/src/Main.jsx
> +    function ToDoListItems (props) {
you can destructure here ({ lists })

2022-10-20 17:48 UTC, andrii1 commented on react/react1/week2/to-do-app/src/Header.jsx
> +        <Timer/>
some files are jsx others js :)

2023-02-23 12:31 UTC, merged